# Generated by Django 3.1.2 on 2020-12-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='response_assert',
            field=models.TextField(verbose_name='断言'),
        ),
    ]
